const num1 = 2;
const num2 = 31;
const multiply = num1 * num2;
console.log(multiply);
const random = (1, 2, 4, 5);
Math.random();
const num3 = 9;
const num4 = 5;
const mod = num3 % num4;
console.log(mod);
const max = (12, 5, 20);
Math.max(); 
